apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka-cluster
  namespace: kafka
  labels:
    app: kafka-cluster
spec:
  kafka:
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
      inter.broker.protocol.version: "3.7"
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: kafka-metrics
          key: kafka-metrics-config.yml
    resources:
      limits:
        memory: 1Gi
        cpu: 1000m
      requests:
        cpu: 200m
        memory: 200Mi
    authorization:
      superUsers:
        - admin
      type: simple
    storage:
      type: jbod
      volumes:
        - id: 0
          type: persistent-claim
          size: 10Gi
          deleteClaim: false
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        authentication:
          type: tls
        port: 9093
        type: internal
        tls: true
    replicas: 3
    version: 3.7.0
  kafkaExporter:
    topicRegex: ".*"
    groupRegex: ".*"
  entityOperator:
    topicOperator: {}
    userOperator:
      secretPrefix: user-
  zookeeper:
    livenessProbe:
      initialDelaySeconds: 360
      timeoutSeconds: 45
    readinessProbe:
      initialDelaySeconds: 360
      timeoutSeconds: 30
    config:
      zookeeper.ssl.hostnameVerification: false
      zookeeper.ssl.quorum.hostnameVerification: false
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: kafka-metrics
          key: zookeeper-metrics-config.yml
    storage:
      deleteClaim: false
      size: 10Gi
      type: persistent-claim
    resources:
      limits:
        memory: 1Gi
        cpu: 1000m
      requests:
        cpu: 200m
        memory: 200Mi
    replicas: 3
